# Generated by Django 5.2.5 on 2025-08-21 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_despacho', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Despacho')),
                ('usuario_solicitante', models.CharField(max_length=150, verbose_name='Usuario Solicitante')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código de Producto')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('cantidad_stock', models.IntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_de_medida', models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Medida')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('stock_minimo', models.IntegerField(default=0, verbose_name='Stock Mínimo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Proveedor')),
                ('contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('codigo_rack', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código de Rack')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('tipo_movimiento', models.CharField(max_length=50, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bodega.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DespachoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bodega.despacho')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodega.producto', verbose_name='Producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodega.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion_rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bodega.rack', verbose_name='Ubicación en Rack'),
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento de Referencia')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodega.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Recepción',
                'verbose_name_plural': 'Recepciones',
            },
        ),
        migrations.CreateModel(
            name='RecepcionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bodega.producto', verbose_name='Producto')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bodega.recepcion')),
            ],
        ),
    ]
