# Generated by Django 4.2.23 on 2025-08-23 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bodega', '0002_area_alter_despacho_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='usuario_registra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra'),
        ),
        migrations.AddField(
            model_name='recepcion',
            name='usuario_registra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registra'),
        ),
    ]
