# Generated by Django 4.2.23 on 2025-08-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0004_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepcion',
            name='documento_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Orden de Compra'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(check=models.Q(('cantidad_stock__gte', 0)), name='stock_no_negativo'),
        ),
    ]
